const ufs = [
  { id: 'br', name: 'brasil', region: 'nacional' },
  { id: 'ac', name: 'acre', region: 'norte' },
  { id: 'al', name: 'alagoas', region: 'nordeste' },
  { id: 'ap', name: 'amapá', region: 'norte' },
  { id: 'am', name: 'amazonas', region: 'norte' },
  { id: 'ba', name: 'bahia', region: 'nordeste' },
  { id: 'ce', name: 'ceará', region: 'nordeste' },
  { id: 'df', name: 'distrito federal', region: 'centro-oeste' },
  { id: 'es', name: 'espírito santo', region: 'sudeste' },
  { id: 'go', name: 'goiás', region: 'centro-oeste' },
  { id: 'ma', name: 'maranhão', region: 'nordeste' },
  { id: 'mt', name: 'mato grosso', region: 'centro-oeste' },
  { id: 'ms', name: 'mato grosso do sul', region: 'centro-oeste' },
  { id: 'mg', name: 'minas gerais', region: 'sudeste' },
  { id: 'pr', name: 'paraná', region: 'sul' },
  { id: 'pb', name: 'paraíba', region: 'nordeste' },
  { id: 'pa', name: 'pará', region: 'norte' },
  { id: 'pe', name: 'pernambuco', region: 'nordeste' },
  { id: 'pi', name: 'piauí', region: 'nordeste' },
  { id: 'rj', name: 'rio de janeiro', region: 'sudeste' },
  { id: 'rn', name: 'rio grande do norte', region: 'nordeste' },
  { id: 'rs', name: 'rio grande do sul', region: 'sul' },
  { id: 'ro', name: 'rondônia', region: 'norte' },
  { id: 'rr', name: 'roraima', region: 'norte' },
  { id: 'sc', name: 'santa catarina', region: 'sul' },
  { id: 'se', name: 'sergipe', region: 'nordeste' },
  { id: 'sp', name: 'são paulo', region: 'sudeste' },
  { id: 'to', name: 'tocantins', region: 'norte' },
  { id: 'zz', name: 'exterior', region: 'exterior' },
];

export default ufs;