const ufs = [
  { id: 'br', name: 'brasil' },
  { id: 'ac', name: 'acre' },
  { id: 'al', name: 'alagoas' },
  { id: 'ap', name: 'amapá' },
  { id: 'am', name: 'amazonas' },
  { id: 'ba', name: 'bahia' },
  { id: 'ce', name: 'ceará' },
  { id: 'df', name: 'distrito federal' },
  { id: 'es', name: 'espírito santo' },
  { id: 'go', name: 'goiás' },
  { id: 'ma', name: 'maranhão' },
  { id: 'mt', name: 'mato grosso' },
  { id: 'ms', name: 'mato grosso do sul' },
  { id: 'mg', name: 'minas gerais' },
  { id: 'pr', name: 'paraná' },
  { id: 'pb', name: 'paraíba' },
  { id: 'pa', name: 'pará' },
  { id: 'pe', name: 'pernambuco' },
  { id: 'pi', name: 'piauí' },
  { id: 'rj', name: 'rio de janeiro' },
  { id: 'rn', name: 'rio grande do norte' },
  { id: 'rs', name: 'rio grande do sul' },
  { id: 'ro', name: 'rondônia' },
  { id: 'rr', name: 'roraima' },
  { id: 'sc', name: 'santa catarina' },
  { id: 'se', name: 'sergipe' },
  { id: 'sp', name: 'são paulo' },
  { id: 'to', name: 'tocantins' },
  { id: 'zz', name: 'exterior' },
];

export default ufs;